/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Clases.Cargo;
import Clases.CargoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Optimus
 */
public class CargoNuevo extends Nuevo {

    /**
     * Creates new form CargoNuevo
     */
    private CargoDAO cargo;
    
    public CargoNuevo() {
        super();
        ModificarTitulos("Cargo");
        cargo = new CargoDAO();
    }
    
    @Override
    public void Guardar(){
        int codigo = cargo.Codigo();
        String nombre = getNombre();
        if(nombre.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese Nombre Cargo");
        }
        else{
            Cargo nuevoC = new Cargo(codigo, nombre);
            if(cargo.Guardar(nuevoC)){
                JOptionPane.showMessageDialog(this, "Nuevo cargo guardado exitosamente");
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al intentar guardar nuevo cargo");
            }
        }
        Inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
