/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Clases.CargoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Optimus
 */
public class CargoElim extends Eliminar {

    /**
     * Creates new form CargoElim
     */
    private CargoDAO cargo;
    
    public CargoElim() {
        super();
        cargo = new CargoDAO();
        ModificarTitulos("Cargo");
        ObtenerListado();
    }
    
    public void ObtenerListado(){
        ArrayList<String> listado = new ArrayList<>();
        cargo.ObtenerCargos(listado);
        BorrarListado();
        AgregarElemento("<Seleccione Cargo>");
        for (int i = 0; i < listado.size(); i++) {
            AgregarElemento(listado.get(i));
        }
    }
    
    @Override
    public void Eliminar(){
        int codigo = getCodigo();
        String nombre = getNombre();
        if(codigo < 1){
            JOptionPane.showMessageDialog(this, "Seleccione un cargo");
        }
        else{
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar cargo " + nombre + "?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if(respuesta == JOptionPane.YES_OPTION){
                if(cargo.EliminarCargo(codigo)){
                    JOptionPane.showMessageDialog(this, "Cargo eliminado exitosamente");
                    ObtenerListado();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error al intentar eliminar cargo");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
