/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

/**
 *
 * @author Optimus
 */
public class Editar extends javax.swing.JInternalFrame {

    public Editar() {
        initComponents();
        Inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblListado = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        butAceptar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        cboListado = new javax.swing.JComboBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setAutoscrolls(true);
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 16, 0, 16, 0};
        jPanel1Layout.rowHeights = new int[] {0, 14, 0, 14, 0, 14, 0};
        jPanel1.setLayout(jPanel1Layout);

        lblListado.setText("Nombre :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(lblListado, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtNombre, gridBagConstraints);

        butAceptar.setText("Guardar Cambios");
        butAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel1.add(butAceptar, gridBagConstraints);

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanel1.add(butCancelar, gridBagConstraints);

        lblNombre.setText("Nuevo Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(lblNombre, gridBagConstraints);

        cboListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboListadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cboListado, gridBagConstraints);

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void butAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceptarActionPerformed
        Editar();
        ObtenerListado();
        Inicializar();
    }//GEN-LAST:event_butAceptarActionPerformed
    
    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        ObtenerListado();
        Inicializar();
    }//GEN-LAST:event_butCancelarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
    }//GEN-LAST:event_formFocusGained
    
    private void cboListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboListadoActionPerformed
        int codigo = cboListado.getSelectedIndex();
        if(codigo > 0){
            String nombre = (String)cboListado.getSelectedItem();
            txtNombre.setText(nombre);
            txtNombre.setEditable(true);
        }
    }//GEN-LAST:event_cboListadoActionPerformed
    
    public void Inicializar(){
        txtNombre.setText("");
        txtNombre.setEditable(false);
    }
    
    public void ModificarTitulos(String nombre){
        setTitle("Editar " + nombre);
        lblListado.setText("Nombre " + nombre);
    }
    
    public void AgregarElemento(String elemento){
        cboListado.addItem(elemento);
    }
    
    public void BorrarListado(){
        cboListado.removeAllItems();
    }
    
    public void Editar(){
        
    }
    
    public void ObtenerListado(){
        
    }
    
    public int getCodigo(){
        return cboListado.getSelectedIndex();
    }
    
    public String getNombre(){
        return txtNombre.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAceptar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JComboBox cboListado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblListado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
