/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Clases.CargoDAO;
import Clases.Funcionario;
import Clases.FuncionarioDAO;
import Clases.NivelDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Optimus
 */
public class FuncionarioNuevo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FuncionarioNuevo
     */
    private CargoDAO cargo;
    private NivelDAO nivel;
    private FuncionarioDAO funcionario;
    
    public FuncionarioNuevo() {
        initComponents();
        cargo = new CargoDAO();
        nivel = new NivelDAO();
        funcionario = new FuncionarioDAO();
        ObtenerListados();
    }
    
    private void Inicializar(){
        txtRut.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtFechaNac.setText("");
        cboCargo.setSelectedIndex(0);
        txtFechaIng.setText("");
        cboNivel.setSelectedIndex(0);
        txtRut.requestFocus();
    }
    
    private void ObtenerListados(){
        cboCargo.removeAllItems();
        cboNivel.removeAllItems();
        cboCargo.addItem("<Seleccione Cargo>");
        cboNivel.addItem("<Seleccione Nivel>");
        ArrayList<String> cargos = new ArrayList<>();
        ArrayList<String> niveles = new ArrayList<>();
        cargo.ObtenerCargos(cargos);
        nivel.ObtenerNiveles(niveles);
        for (int i = 0; i < cargos.size(); i++) {
            cboCargo.addItem(cargos.get(i));
        }
        for (int i = 0; i < niveles.size(); i++) {
            cboNivel.addItem(niveles.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboCargo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboNivel = new javax.swing.JComboBox();
        butGuardar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();
        txtFechaNac = new javax.swing.JFormattedTextField();
        txtFechaIng = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo Funcionario");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 16, 0, 16, 0};
        jPanel1Layout.rowHeights = new int[] {0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("RUT :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtRut, gridBagConstraints);

        jLabel2.setText("Nombres :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtNombre, gridBagConstraints);

        jLabel3.setText("Apellidos :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtApellido, gridBagConstraints);

        jLabel4.setText("Fecha Nacimiento :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Cargo :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel5, gridBagConstraints);

        cboCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cboCargo, gridBagConstraints);

        jLabel6.setText("Fecha Ingreso :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Nivel :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel7, gridBagConstraints);

        cboNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cboNivel, gridBagConstraints);

        butGuardar.setText("Guardar Funcionario");
        butGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        jPanel1.add(butGuardar, gridBagConstraints);

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        jPanel1.add(butCancelar, gridBagConstraints);

        txtFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtFechaNac, gridBagConstraints);

        txtFechaIng.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtFechaIng, gridBagConstraints);

        jLabel8.setText("(dd-mm-aaaa)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel9.setText("(dd-mm-aaaa)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        jPanel1.add(jLabel9, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGuardarActionPerformed
        String rut = txtRut.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String fechaNac = txtFechaNac.getText();
        int codCargo = cboCargo.getSelectedIndex();
        String fechaIng = txtFechaIng.getText();
        int codNivel = cboNivel.getSelectedIndex();
        int estado = 1;
        if(rut.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese RUT");
            txtRut.requestFocus();
        }
        else if(!Login.ValidarRut(rut)){
            JOptionPane.showMessageDialog(this, "RUT no válido");
            txtRut.requestFocus();
        }
        else if(nombre.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese Nombre");
            txtNombre.requestFocus();
        }
        else if(apellido.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese Apellido");
            txtApellido.requestFocus();
        }
        else if(fechaNac.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese Fecha Nacimiento");
            txtFechaNac.requestFocus();
        }
        else if(codCargo < 1){
            JOptionPane.showMessageDialog(this, "Seleccione Cargo");
            cboCargo.requestFocus();
        }
        else if(fechaIng.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese Fecha Ingreso");
            txtFechaIng.requestFocus();
        }
        else{
            Funcionario nuevo = new Funcionario(rut, nombre + "_" + apellido, fechaNac, codCargo, fechaIng, codNivel, estado);
            if(funcionario.Guardar(nuevo)){
                JOptionPane.showMessageDialog(this, "Funcionario registrado exitosamente");
                Inicializar();
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al intentar guardar funcionario");
            }
        }
    }//GEN-LAST:event_butGuardarActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        Inicializar();
    }//GEN-LAST:event_butCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butGuardar;
    private javax.swing.JComboBox cboCargo;
    private javax.swing.JComboBox cboNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JFormattedTextField txtFechaIng;
    private javax.swing.JFormattedTextField txtFechaNac;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
