/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Clases.Nivel;
import Clases.NivelDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Optimus
 */
public class NivelEditar extends Editar {

    /**
     * Creates new form NivelEditar
     */
    private NivelDAO nivel;
    
    public NivelEditar() {
        super();
        nivel = new NivelDAO();
        ObtenerListado();
        ModificarTitulos("Nivel");
    }
    
    @Override
    public void ObtenerListado(){
        ArrayList<String> listado = new ArrayList<>();
        nivel.ObtenerNiveles(listado);
        BorrarListado();
        AgregarElemento("<Seleccione Nivel>");
        for (int i = 0; i < listado.size(); i++) {
            AgregarElemento(listado.get(i));
        }
    }
    
    @Override
    public void Editar(){
        int codigo = getCodigo();
        String nombre = getNombre();
        if(codigo < 1){
            JOptionPane.showMessageDialog(this, "Seleccione un nivel");
        }
        else if(nombre.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese nombre nivel");
        }
        else{
            Nivel edit = new Nivel(codigo, nombre);
            if(nivel.ActualizarNivel(edit)){
                JOptionPane.showMessageDialog(this, "Nivel modificado exitosamente");
                Inicializar();
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al intentar modificar nivel");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
