/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Clases.Perfil;
import Clases.PerfilDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Optimus
 */
public class PerfilNuevo extends Nuevo {

    /**
     * Creates new form PerfilNuevo
     */
    private PerfilDAO perfil;
    
    public PerfilNuevo() {
        super();
        ModificarTitulos("Perfil");
        perfil = new PerfilDAO();
    }
    
    @Override
    public void Guardar(){
        int codigo = perfil.Codigo();
        String nombre = getNombre();
        if(nombre.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese Nombre Perfil");
        }
        else{
            Perfil nuevoP = new Perfil(codigo, nombre);
            if(perfil.Guardar(nuevoP)){
                JOptionPane.showMessageDialog(this, "Nuevo perfil guardado exitosamente");
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al intentar guardar nuevo perfil");
            }
        }
        Inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
