/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Clases.Perfil;
import Clases.PerfilDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Optimus
 */
public class PerfilEditar extends Editar {

    /**
     * Creates new form PerfilEditar
     */
    private PerfilDAO perfil;
    
    public PerfilEditar() {
        super();
        perfil = new PerfilDAO();
        ObtenerListado();
        ModificarTitulos("Perfil");
    }
    
    @Override
    public void ObtenerListado(){
        ArrayList<String> listado = new ArrayList<>();
        perfil.ObtenerPerfiles(listado);
        BorrarListado();
        AgregarElemento("<Seleccione Perfil>");
        for (int i = 0; i < listado.size(); i++) {
            AgregarElemento(listado.get(i));
        }
    }
    
    @Override
    public void Editar(){
        int codigo = getCodigo();
        String nombre = getNombre();
        if(codigo < 1){
            JOptionPane.showMessageDialog(this, "Seleccione un perfil");
        }
        else if(nombre.length() == 0){
            JOptionPane.showMessageDialog(this, "Ingrese Nombre Perfil");
        }
        else{
            Perfil edit = new Perfil(codigo, nombre);
            if(perfil.ActualizarPerfil(edit)){
                JOptionPane.showMessageDialog(this, "Perfil modificado exitosamente");
                Inicializar();
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al intentar modificar perfil");
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
