/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Clases.Funcionario;
import Clases.FuncionarioDAO;
import Clases.Permiso;
import Clases.PermisoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Optimus
 */
public class PermisoEliminar extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioEliminar
     */
    public PermisoEliminar() {
        initComponents();
        CargarDatos();
    }
    
    public void ModificarTitulos(String nombre){
        setTitle("Eliminar " + nombre);
        butEliminar.setText("Eliminar " + nombre);
    }
    
    private void CargarDatos(){
        DefaultTableModel modelo = (DefaultTableModel) tabPermisos.getModel();
        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        tabPermisos.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumn col = tabPermisos.getColumn("Código");
        col.setMinWidth(50);
        col.setMaxWidth(50);
        col.setCellRenderer(centrado);
        col = tabPermisos.getColumn("RUT Funcionario");
        col.setMinWidth(110);
        col.setMaxWidth(110);
        col = tabPermisos.getColumn("Cant. Días");
        col.setMinWidth(70);
        col.setMaxWidth(70);
        col.setCellRenderer(centrado);
        col = tabPermisos.getColumn("Fecha Emisión");
        col.setMinWidth(100);
        col.setMaxWidth(100);
        col.setCellRenderer(centrado);
        for (int i = modelo.getRowCount()-1; i >= 0; i--) {
                modelo.removeRow(i);
        }
        ArrayList<Permiso> permisos = PermisoDAO.ObtenerPermisos();
        for (int i = 0; i < permisos.size(); i++) {
            int codigo = permisos.get(i).getCodigo();
            String rutFun = permisos.get(i).getRutFuncionario();
            Funcionario fun = FuncionarioDAO.BuscarFuncionario(rutFun);
            String [] nombre = fun.getNombre().split("_");
            int cantDias = permisos.get(i).getDias();
            String fecha = permisos.get(i).getFecha();
            String resolucion = permisos.get(i).getResolucion();
            modelo.addRow(new Object[]{codigo, rutFun, nombre[0], nombre[1], cantDias, fecha, resolucion});
        }
    }
    
    public void Eliminar(){
        int indice = tabPermisos.getSelectedRow();
        if(indice != -1){
            int codigo = Integer.parseInt(tabPermisos.getModel().getValueAt(indice, 0).toString());
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar permiso? ", "Confirmación", JOptionPane.YES_NO_OPTION);
            if(respuesta == JOptionPane.YES_OPTION){
                if(PermisoDAO.EliminarPermiso(codigo)){
                    CargarDatos();
                    JOptionPane.showMessageDialog(this, "Permiso eliminado exitosamente");
                }
            }
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabPermisos = new javax.swing.JTable();
        butEliminar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Permiso");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tabPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "RUT Funcionario", "Nombres", "Apellidos", "Cant. Días", "Fecha Emisión", "Resolución"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabPermisos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        butEliminar.setText("Eliminar");
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(butEliminar, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_butEliminarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
    }//GEN-LAST:event_formInternalFrameClosed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabPermisos;
    // End of variables declaration//GEN-END:variables
}
