/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Clases.Funcionario;
import Clases.FuncionarioDAO;
import java.util.ArrayList;
import Clases.CargoDAO;
import Clases.Permiso;
import Clases.PermisoDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Catherine
 */
public class PermisoEditar extends javax.swing.JInternalFrame {

    /**
     * Creates new form PermisoNuevo
     */
    private DefaultListModel<String> modelo;
    
    public PermisoEditar() {
        initComponents();
        lstFechas.setPreferredSize(null);
        modelo = new DefaultListModel<>();
        lstFechas.setModel(modelo);
        Inicializar();
    }
    
    private void Activar(){
        cboCantidad.setEnabled(true);
        txtFecha.setEnabled(true);
        butAgregar.setEnabled(true);
        butQuitar.setEnabled(true);
        txtMotivo.setEditable(true);
    }
    
    private void Desactivar(){
        cboCantidad.setEnabled(false);
        txtFecha.setEnabled(false);
        butAgregar.setEnabled(false);
        butQuitar.setEnabled(false);
        txtMotivo.setEditable(false);
    }
    
    private void Inicializar(){
        cboCodigo.removeAllItems();
        cboCodigo.addItem("<Seleccione Código>");
        ArrayList <Permiso> permisos = PermisoDAO.ObtenerPendientes();
        for (int i = 0; i < permisos.size(); i++) {
            cboCodigo.addItem(permisos.get(i).getCodigo());
        }
        cboCantidad.removeAllItems();
        cboCantidad.addItem("<Seleccione Cantidad>");
        txtFechaEmision.setText("");
        txtFecha.setDate(null);
        modelo.removeAllElements();
        txtMotivo.setText("");
        Desactivar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        butAceptar = new javax.swing.JButton();
        Cargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        CantDias = new javax.swing.JLabel();
        butCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        butAgregar = new javax.swing.JButton();
        butQuitar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboCodigo = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstFechas = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        cboCantidad = new javax.swing.JComboBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Permiso");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 16, 0, 16, 0, 16, 0};
        jPanel1Layout.rowHeights = new int[] {0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0, 14, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Rut Funcionario :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nombres :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel2, gridBagConstraints);

        txtRut.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtRut, gridBagConstraints);

        butAceptar.setText("Actualizar Permiso");
        butAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(butAceptar, gridBagConstraints);

        Cargo.setText("Cargo :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(Cargo, gridBagConstraints);

        txtCargo.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtCargo, gridBagConstraints);

        CantDias.setText("Cantidad de días :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(CantDias, gridBagConstraints);

        butCancelar.setText("Cancelar");
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(butCancelar, gridBagConstraints);

        jLabel3.setText("Motivo :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel3, gridBagConstraints);

        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        jScrollPane2.setViewportView(txtMotivo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jScrollPane2, gridBagConstraints);

        jLabel4.setText("Apellidos :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel4, gridBagConstraints);

        txtApellido.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtApellido, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtFecha, gridBagConstraints);

        jLabel5.setText("Fechas :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel5, gridBagConstraints);

        butAgregar.setText("Agregar");
        butAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAgregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(butAgregar, gridBagConstraints);

        butQuitar.setText("Quitar");
        butQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butQuitarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel1.add(butQuitar, gridBagConstraints);

        txtNombre.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(txtNombre, gridBagConstraints);

        jLabel6.setText("Código Permiso :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel6, gridBagConstraints);

        cboCodigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCodigoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(cboCodigo, gridBagConstraints);

        lstFechas.setAutoscrolls(false);
        lstFechas.setMaximumSize(new java.awt.Dimension(33, 50));
        lstFechas.setMinimumSize(new java.awt.Dimension(33, 50));
        lstFechas.setPreferredSize(new java.awt.Dimension(33, 50));
        lstFechas.setVisibleRowCount(5);
        jScrollPane4.setViewportView(lstFechas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jScrollPane4, gridBagConstraints);

        jLabel7.setText("Fecha Emisión :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel7, gridBagConstraints);

        txtFechaEmision.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtFechaEmision, gridBagConstraints);

        cboCantidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCantidad.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cboCantidad, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceptarActionPerformed
        if(cboCodigo.getSelectedIndex() > 0){
            int codigo = Integer.parseInt(cboCodigo.getSelectedItem().toString());
            String rut = txtRut.getText();
            String dias = cboCantidad.getSelectedItem().toString();
            ArrayList<String> fechas = new ArrayList<>();
            for (int i = 0; i < modelo.getSize(); i++) {
                fechas.add(modelo.getElementAt(i));
            }
            String motivo = txtMotivo.getText();
            if(cboCantidad.getSelectedIndex() < 1){
                JOptionPane.showMessageDialog(this, "Seleccione una cantidad de dias");
                cboCantidad.requestFocus(); 
            }
            else if(fechas.isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese al menos una fecha");
                txtFecha.requestFocus();
            }
            else if(motivo.length() == 0){
                JOptionPane.showMessageDialog(this, "Ingrese un motivo");
                txtMotivo.requestFocus();
            }
            else{
                int numDias = Integer.parseInt(dias);
                if(fechas.size() == numDias){
                    Permiso editar = new Permiso(codigo, rut, Login.user.getRut(), numDias, motivo, fechas);
                    if(PermisoDAO.ActualizarPermiso(editar)){
                        JOptionPane.showMessageDialog(this,"Permiso modificado exitosamente");
                        Inicializar();
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Error al intentar modificar permiso");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"El número de fechas no coincide con la cantidad de días");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione un código");
            cboCodigo.requestFocus();
        }
    }//GEN-LAST:event_butAceptarActionPerformed

    private void butAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAgregarActionPerformed
        try{
            int dias = Integer.parseInt(cboCantidad.getSelectedItem().toString());
            if(modelo.getSize() < dias){
                String formato = txtFecha.getDateFormatString();
                Date fecha = txtFecha.getDate();
                if(fecha != null){
                    SimpleDateFormat sdf = new SimpleDateFormat(formato);
                    String fechaString = sdf.format(fecha);
                    if(!modelo.contains(fechaString)){
                        modelo.addElement(fechaString);
                        txtFecha.setDate(null);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Fecha ya ingresada");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Seleccione una fecha");
                    txtFecha.setDate(null);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Exceso en cantidad de días");
                txtFecha.requestFocus();
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Seleccione una cantidad de dias");
            cboCantidad.requestFocus(); 
        }
    }//GEN-LAST:event_butAgregarActionPerformed

    private void butQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butQuitarActionPerformed
        if(lstFechas.getSelectedIndex() != -1){
            modelo.remove(lstFechas.getSelectedIndex());
        }
    }//GEN-LAST:event_butQuitarActionPerformed

    private void cboCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCodigoActionPerformed
        if(cboCodigo.getSelectedIndex() > 0){
            int codigo = Integer.parseInt(cboCodigo.getSelectedItem().toString());
            Permiso permiso = PermisoDAO.BuscarPermniso(codigo);
            if(permiso != null){
                String rut = permiso.getRutFuncionario();
                Funcionario fun = FuncionarioDAO.BuscarFuncionario(rut);
                String [] nombre = fun.getNombre().split("_");
                txtRut.setText(rut);
                txtNombre.setText(nombre[0]);
                txtApellido.setText(nombre[1]);
                txtCargo.setText(CargoDAO.ObtenerNombre(fun.getCargo()));
                txtFechaEmision.setText(permiso.getFecha());
                SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                try {
                    Date date = formato.parse(permiso.getFecha());
                    txtFecha.setMinSelectableDate(date);
                } catch (ParseException ex) {
                    Logger.getLogger(PermisoEditar.class.getName()).log(Level.SEVERE, null, ex);
                }
                String anyo = permiso.getFecha().split("-")[2];
                int total = PermisoDAO.ObtenerTotal(rut, anyo);
                cboCantidad.removeAllItems();
                cboCantidad.addItem("<Seleccione Cantidad>");
                for (int i = 1; i <= (6 - total); i++) {
                    cboCantidad.addItem(i);
                }
                if(permiso.getDias() <= (6-total)){
                    cboCantidad.setSelectedIndex(permiso.getDias());
                }
                txtMotivo.setText(permiso.getMotivo());
                ArrayList<String> fechas = PermisoDAO.ObtenerFechas(codigo);
                modelo.removeAllElements();
                for (int i = 0; i < fechas.size(); i++) {
                    modelo.addElement(fechas.get(i));
                }
                lstFechas.setModel(modelo);
            }
            Activar();
        }
        else{
            txtRut.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtCargo.setText("");
            cboCantidad.removeAllItems();
            cboCantidad.addItem("<Seleccione Cantidad>");
            txtMotivo.setText("");
            modelo.removeAllElements();
            Desactivar();
        }
    }//GEN-LAST:event_cboCodigoActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        Inicializar();
    }//GEN-LAST:event_butCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantDias;
    private javax.swing.JLabel Cargo;
    private javax.swing.JButton butAceptar;
    private javax.swing.JButton butAgregar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JButton butQuitar;
    private javax.swing.JComboBox cboCantidad;
    private javax.swing.JComboBox cboCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList lstFechas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCargo;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
